# Generated by Django 4.2.8 on 2025-07-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailOTP',
            new_name='email_otp',
        ),
    ]
