# Generated by Django 4.2.8 on 2025-07-18 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otp_totp', '0003_add_timestamps'),
        ('auth_core', '0002_rename_emailotp_email_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorAuthDevice',
            fields=[
                ('totpdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='otp_totp.totpdevice')),
            ],
            options={
                'verbose_name': 'Two Factor Auth Device',
                'verbose_name_plural': 'Two Factor Auth Devices',
            },
            bases=('otp_totp.totpdevice',),
        ),
    ]
