version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=app
      - DB_PASS=app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5430:5432"

volumes:
  postgres_data:
