version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    image: chbudi9/nemasapp
    volumes:
      - ./nemas:/nemas
      - /etc/letsencrypt:/etc/letsencrypt:ro
    env_file:
      - .env
    depends_on:
      - redis
    expose:
      - "8000"
    command: >
      sh -c "
        python manage.py wait_for_db &&
        if [ \"$USE_HTTPS\" = \"true\" ]; then
          granian --interface asgi ----ssl-certificate /etc/letsencrypt/live/nemas.id/fullchain.pem --ssl-keyfile /etc/letsencrypt/live/nemas.id/privkey.pem --port 8000 app.asgi:application
        else
          granian --interface asginl --host 0.0.0.0 --port 8000 --reload app.asgi:application
        fi
      "

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/archive/nemas.id-0001/fullchain1.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/archive/nemas.id-0001/privkey1.pem:/etc/ssl/private/privkey.pem:ro
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    image: chbudi9/nemasapp
    command: sh -c "celery -A app worker --loglevel=info & celery -A app beat --scheduler django_celery_beat.schedulers:DatabaseScheduler --loglevel=info"
    volumes:
      - ./nemas:/nemas # Mount the local directory to the container
    env_file:
      - .env
    depends_on:
      - redis

  flower:
    image: chbudi9/nemasapp
    command: celery -A app --broker=redis://redis/0 flower --port=5555 --db=/flower_db --persistent=True
    volumes:
      - ./nemas:/nemas # Mount the local directory to the container
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      - redis

  # web:
  #   image: idrislabdev/nemas-admin-docker:v1.0
  #   container_name: web.nemas
  #   restart: always
  #   ports:
  #     - 5005:5005
