version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./nemas:/nemas # Mount the local directory to the container
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - USE_HTTPS=${USE_HTTPS:-false}
    command: >
      sh -c "python manage.py wait_for_db &&
             if [ \"$USE_HTTPS\" = \"true\" ]; then
               nginx && gunicorn --certfile=/etc/ssl/certs/selfsigned.crt --keyfile=/etc/ssl/private/selfsigned.key --bind 0.0.0.0:8000 --cert-reqs=0 app.wsgi:application;
             else
               python manage.py runserver 0.0.0.0:8000;
             fi"

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
