version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    image: chbudi9/nemasapp
    volumes:
      - ./nemas:/nemas
      - /etc/letsencrypt:/etc/letsencrypt:ro
    env_file:
      - .env
    depends_on:
      - redis
    command: |
      sh -c "python manage.py wait_for_db &&
            if [ \"$USE_HTTPS\" = \"true\" ]; then
              gunicorn --bind 0.0.0.0:8000 app.wsgi:application
            else
              python manage.py runserver 0.0.0.0:8000
            fi"

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /letsencrypt/live/nemas.id-0001/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /letsencrypt/live/nemas.id-0001/privkey.pem:/etc/ssl/private/privkey.pem:ro
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    image: chbudi9/nemasapp
    command: sh -c "celery -A app worker --loglevel=info & celery -A app beat --scheduler django_celery_beat.schedulers:DatabaseScheduler --loglevel=info"
    volumes:
      - ./nemas:/nemas # Mount the local directory to the container
    env_file:
      - .env
    depends_on:
      - redis

  flower:
    image: chbudi9/nemasapp
    command: celery -A app --broker=redis://redis/0 flower --port=5555 --db=/flower_db --persistent=True
    volumes:
      - ./nemas:/nemas # Mount the local directory to the container
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      - redis

  # web:
  #   image: idrislabdev/nemas-admin-docker:v1.0
  #   container_name: web.nemas
  #   restart: always
  #   ports:
  #     - 5005:5005
