version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - DB_HOST=nemasdb.cr2my0uo8cbt.ap-southeast-1.rds.amazonaws.com
      - DB_NAME=nemasdb
      - DB_USER=postgres
      - DB_PASS=exXTF6COcKZEJjfnhMvU
      - SELENIUM_URL=http://app.selenium:4444/wd/hub
    command: >
      sh -c "python manage.py wait_for_db &&
             gunicorn --certfile=/etc/ssl/certs/selfsigned.crt --keyfile=/etc/ssl/private/selfsigned.key --bind 0.0.0.0:8000 --cert-reqs=0 app.wsgi:application"
  # web.nemas:
  #   image: idrislabdev/nemas-admin-docker:v1.0
  #   container_name: web.nemas
  #   restart: always
  #   ports:
  #     - 5005:5005
volumes:
  postgres_data:
