# Generated by Django 4.2.8 on 2025-07-26 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fee_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percentage or fixed amount', max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='ROI rate as a percentage (e.g., 5.00 for 5%)', max_digits=5)),
                ('duration_days', models.PositiveIntegerField(help_text='Duration for ROI calculation in days')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_invested', models.DateField(auto_now_add=True)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('return_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date_returned', models.DateField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('admin_fee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investment.adminfee')),
                ('investment_return', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investment.investmentreturn')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
