# Generated by Django 4.2.8 on 2025-07-26 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_adminfee_investmentreturn_delete_celerytasks'),
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmenttransaction',
            name='admin_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.adminfee'),
        ),
        migrations.AlterField(
            model_name='investmenttransaction',
            name='investment_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.investmentreturn'),
        ),
        migrations.DeleteModel(
            name='AdminFee',
        ),
        migrations.DeleteModel(
            name='InvestmentReturn',
        ),
    ]
