# Generated by Django 4.2.8 on 2025-07-28 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0049_adminfee_transaction_type_alter_adminfee_id'),
        ('investment', '0002_alter_investmenttransaction_admin_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=15)),
                ('weight_invested', models.DecimalField(blank=True, decimal_places=4, max_digits=10)),
                ('date_invested', models.DateField(auto_now_add=True)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('investment_weight_return', models.DecimalField(blank=True, decimal_places=4, max_digits=10)),
                ('return_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date_returned', models.DateField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investment_return', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.investmentreturn')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='InvestmentTransaction',
        ),
    ]
