# Generated by Django 4.2.8 on 2025-07-28 02:06

import core.fields.uuidv7_field
from django.db import migrations
import uuid6


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_transactionmodel_delete_investmenttransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmodel',
            name='fee_amount',
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='transaction_id',
            field=core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
