# Generated by Django 4.2.8 on 2025-08-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_remove_transactionmodel_fee_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionmodel',
            old_name='investment_weight_return',
            new_name='return_weight',
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
