# Generated by Django 4.2.8 on 2025-07-05 09:25

import core.fields.uuidv7_field
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='monthly_user_summary',
            fields=[
                ('daily_user_summary_id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('summary_month', models.DateField()),
                ('total_buy', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('total_sell', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('latest_buy', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('latest_sell', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'summary_month')},
            },
        ),
        migrations.CreateModel(
            name='daily_user_summary',
            fields=[
                ('daily_user_summary_id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('summary_date', models.DateField()),
                ('total_buy', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('total_sell', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('latest_buy', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('latest_sell', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'summary_date')},
            },
        ),
    ]
