# Generated by Django 4.2.8 on 2025-07-05 09:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='monthly_user_summary',
            new_name='daily_summary',
        ),
        migrations.RenameModel(
            old_name='daily_user_summary',
            new_name='monthly_summary',
        ),
        migrations.RenameField(
            model_name='daily_summary',
            old_name='summary_month',
            new_name='summary_date',
        ),
        migrations.RenameField(
            model_name='monthly_summary',
            old_name='summary_date',
            new_name='summary_month',
        ),
        migrations.AlterUniqueTogether(
            name='daily_summary',
            unique_together={('user', 'summary_date')},
        ),
        migrations.AlterUniqueTogether(
            name='monthly_summary',
            unique_together={('user', 'summary_month')},
        ),
    ]
