# Generated by Django 4.2.8 on 2024-11-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='information_article',
            fields=[
                ('information_article_id', models.AutoField(primary_key=True, serialize=False)),
                ('information_article_name', models.CharField(max_length=255)),
                ('information_article_body', models.TextField(blank=True, null=True)),
                ('article_date', models.DateTimeField(blank=True, null=True)),
                ('article_publish_date', models.DateTimeField(blank=True, null=True)),
                ('article_updated_date', models.DateTimeField(blank=True, null=True)),
                ('article_author', models.CharField(blank=True, max_length=255, null=True)),
                ('article_source', models.URLField(blank=True, max_length=255, null=True)),
                ('article_link', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
