# Generated by Django 4.2.8 on 2024-09-23 15:45

import core.fields.uuidv7_field
from django.db import migrations, models
import uuid6


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_createtime_gold_create_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='gold_price_source',
            fields=[
                ('gold_price_source_id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('gold_price_source', models.CharField(default='', max_length=50)),
                ('gold_price_weight', models.IntegerField(default=1)),
                ('gold_price_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='gold_cert_price',
            name='cert_code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
