# Generated by Django 4.2.8 on 2024-11-25 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_information_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information_promo',
            old_name='id_promo',
            new_name='promo_id',
        ),
    ]
