# Generated by Django 4.2.8 on 2024-12-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_celerytasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order_promo',
            new_name='gold_promo',
        ),
        migrations.RenameField(
            model_name='gold_promo',
            old_name='order_promo_active',
            new_name='gold_promo_active',
        ),
        migrations.RenameField(
            model_name='gold_promo',
            old_name='order_promo_amt',
            new_name='gold_promo_amt',
        ),
        migrations.RenameField(
            model_name='gold_promo',
            old_name='order_promo_amt_pct',
            new_name='gold_promo_amt_pct',
        ),
        migrations.RenameField(
            model_name='gold_promo',
            old_name='order_promo_code',
            new_name='gold_promo_code',
        ),
        migrations.RenameField(
            model_name='gold_promo',
            old_name='order_promo_description',
            new_name='gold_promo_description',
        ),
        migrations.RenameField(
            model_name='gold_promo',
            old_name='order_promo_end_date',
            new_name='gold_promo_end_date',
        ),
        migrations.RenameField(
            model_name='gold_promo',
            old_name='order_promo_id',
            new_name='gold_promo_id',
        ),
        migrations.RenameField(
            model_name='gold_promo',
            old_name='order_promo_max_amt',
            new_name='gold_promo_max_amt',
        ),
        migrations.RenameField(
            model_name='gold_promo',
            old_name='order_promo_max_weight',
            new_name='gold_promo_max_weight',
        ),
        migrations.RenameField(
            model_name='gold_promo',
            old_name='order_promo_min_amt',
            new_name='gold_promo_min_amt',
        ),
        migrations.RenameField(
            model_name='gold_promo',
            old_name='order_promo_min_weight',
            new_name='gold_promo_min_weight',
        ),
        migrations.RenameField(
            model_name='gold_promo',
            old_name='order_promo_start_date',
            new_name='gold_promo_start_date',
        ),
        migrations.RenameField(
            model_name='gold_promo',
            old_name='order_promo_weight',
            new_name='gold_promo_weight',
        ),
        migrations.AddField(
            model_name='information_article',
            name='article_background',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
