# Generated by Django 4.2.8 on 2024-12-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gold_price_gold_price_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_code', models.CharField(max_length=50, unique=True)),
                ('bank_name', models.CharField(max_length=255, unique=True)),
                ('bank_merchant_code', models.CharField(max_length=10, unique=True)),
                ('bank_logo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_active', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.CharField(max_length=255)),
                ('upd_time', models.DateTimeField(auto_now=True)),
                ('upd_user', models.CharField(max_length=255)),
            ],
        ),
    ]
