# Generated by Django 4.2.8 on 2024-10-05 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_city_city_id_alter_district_district_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sub_district_post_code',
            new_name='postal_code',
        ),
    ]
