# Generated by Django 4.2.8 on 2024-10-05 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_sub_district_post_code_postal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postal_code',
            old_name='post_code_id',
            new_name='postal_code_id',
        ),
    ]
