# Generated by Django 4.2.8 on 2024-12-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_information_promo_show_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold',
            name='gold_image_1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='gold',
            name='gold_image_2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='gold',
            name='gold_image_3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='gold',
            name='gold_image_4',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='gold',
            name='gold_image_5',
            field=models.CharField(default='', max_length=255),
        ),
    ]
