# Generated by Django 4.2.8 on 2024-12-28 07:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_gold_gold_image_1_gold_gold_image_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gold',
            old_name='certificate_number',
            new_name='certificate_code',
        ),
        migrations.AddField(
            model_name='gold',
            name='certificate_weight',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10),
        ),
    ]
