# Generated by Django 4.2.8 on 2025-01-05 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_certificate_number_gold_certificate_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gold',
            old_name='certificate_code',
            new_name='certificate_number',
        ),
    ]
