# Generated by Django 4.2.8 on 2025-01-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_certificate_code_gold_certificate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bank_va_range_end',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_va_range_start',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
