# Generated by Django 4.2.8 on 2025-01-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_bank_bank_va_range_end_bank_bank_va_range_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bank_closed_va_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_open_va_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
