# Generated by Django 4.2.8 on 2025-02-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_bank_bank_closed_va_code_bank_bank_open_va_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bank_create_code_va',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_closed_va_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_open_va_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_va_range_end',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_va_range_start',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
