# Generated by Django 4.2.8 on 2025-02-22 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_delivery_shipment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_shipment_content',
            name='delivery_partner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.delivery_partner'),
        ),
        migrations.CreateModel(
            name='delivery_partner_district',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_code', models.CharField(max_length=50, unique=True)),
                ('district_code', models.CharField(max_length=50)),
                ('district_name', models.CharField(max_length=150)),
                ('zone_code', models.CharField(max_length=50)),
                ('provinsi_code', models.CharField(max_length=50)),
                ('city_name', models.CharField(max_length=50)),
                ('tlc_branch_code', models.CharField(max_length=50)),
                ('province_name', models.CharField(max_length=50)),
                ('delivery_partner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.delivery_partner')),
            ],
        ),
    ]
