# Generated by Django 4.2.8 on 2025-02-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_delivery_shipment_content_delivery_partner_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_partner_district',
            name='city_code',
            field=models.CharField(max_length=50),
        ),
    ]
