# Generated by Django 4.2.8 on 2025-02-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_delivery_partner_district_city_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_partner_district',
            name='zone_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='delivery_shipment_content',
            name='shipment_content_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='delivery_shipment_content',
            name='shipment_type_code',
            field=models.CharField(max_length=50),
        ),
    ]
