# Generated by Django 4.2.8 on 2025-02-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_delivery_partner_district_zone_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_partner_district',
            name='city_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='delivery_partner_district',
            name='district_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='delivery_partner_district',
            name='district_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='delivery_partner_district',
            name='provinsi_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
