# Generated by Django 4.2.8 on 2025-02-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_delivery_partner_district_city_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='address_pickup',
            fields=[
                ('address_pickup_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address_pickup_address', models.CharField(max_length=255)),
                ('address_pickup_name', models.CharField(max_length=255)),
            ],
        ),
    ]
