# Generated by Django 4.2.8 on 2025-02-27 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_address_pickup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='address_pickup',
            new_name='customer_address_pickup',
        ),
        migrations.RenameField(
            model_name='customer_address_pickup',
            old_name='address_pickup_address',
            new_name='customer_address_pickup_address',
        ),
        migrations.RenameField(
            model_name='customer_address_pickup',
            old_name='address_pickup_id',
            new_name='customer_address_pickup_id',
        ),
        migrations.RenameField(
            model_name='customer_address_pickup',
            old_name='address_pickup_name',
            new_name='customer_address_pickup_name',
        ),
    ]
