# Generated by Django 4.2.8 on 2025-03-12 20:37

import core.fields.uuidv7_field
from django.db import migrations, models
import uuid6


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_address_pickup_customer_address_pickup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cert',
            fields=[
                ('cert_id', models.AutoField(primary_key=True, serialize=False)),
                ('cert_name', models.CharField(max_length=255)),
                ('cert_code', models.CharField(max_length=50)),
                ('gold_weight', models.IntegerField()),
                ('cert_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='gold_cert_detail_price',
            fields=[
                ('id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('gold_cert_code', models.CharField(max_length=50)),
                ('gold_weight', models.IntegerField()),
                ('include_stock', models.BooleanField(default=True)),
                ('gold_cert_status', models.CharField(default='active', max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.CharField(max_length=255)),
            ],
        ),
    ]
