# Generated by Django 4.2.8 on 2025-03-12 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_cert_gold_cert_detail_price'),
        ('order', '0020_remove_order_gold_detail_certificate_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gold_cert_price',
        ),
        migrations.RemoveField(
            model_name='gold',
            name='certificate_number',
        ),
        migrations.AddField(
            model_name='gold',
            name='product_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gold_cert_detail_price',
            name='gold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gold'),
        ),
        migrations.AddField(
            model_name='gold_cert_detail_price',
            name='gold_cert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cert'),
        ),
    ]
