# Generated by Django 4.2.8 on 2025-03-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_gold_cert_detail_price_fee_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold',
            name='create_user',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='gold',
            name='upd_user',
            field=models.UUIDField(),
        ),
    ]
