# Generated by Django 4.2.8 on 2025-03-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_gold_create_user_alter_gold_upd_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='gold',
            name='create_user',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gold',
            name='upd_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='gold',
            name='upd_user',
            field=models.CharField(max_length=255),
        ),
    ]
