# Generated by Django 4.2.8 on 2025-03-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_gold_create_time_alter_gold_create_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gold',
            name='upd_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
