# Generated by Django 4.2.8 on 2025-03-15 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_gold_create_time_alter_gold_upd_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='create_user_mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='upd_user_mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cert',
            name='create_user_mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cert',
            name='upd_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cert',
            name='upd_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='cert',
            name='upd_user_mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gold',
            name='create_user_mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gold',
            name='upd_user_mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gold_cert_detail_price',
            name='create_user_mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gold_cert_detail_price',
            name='upd_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gold_cert_detail_price',
            name='upd_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='gold_cert_detail_price',
            name='upd_user_mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gold_price_config',
            name='create_user_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gold_price_config',
            name='gpc_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gold_price_config',
            name='upd_user_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gold_promo',
            name='create_user_mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gold_promo',
            name='upd_user_mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='information_article',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information_article',
            name='create_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='information_article',
            name='create_user_mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='information_article',
            name='upd_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='information_article',
            name='upd_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='information_article',
            name='upd_user_mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='information_customer_service',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information_customer_service',
            name='create_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='information_customer_service',
            name='create_user_mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='information_customer_service',
            name='upd_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='information_customer_service',
            name='upd_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='information_customer_service',
            name='upd_user_mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='information_educational',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information_educational',
            name='create_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='information_educational',
            name='create_user_mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='information_educational',
            name='upd_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='information_educational',
            name='upd_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='information_educational',
            name='upd_user_mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='information_faq',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information_faq',
            name='create_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='information_faq',
            name='create_user_mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='information_faq',
            name='upd_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='information_faq',
            name='upd_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='information_faq',
            name='upd_user_mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='information_promo',
            name='create_user_mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='information_promo',
            name='upd_user_mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='information_rating',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information_rating',
            name='create_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='information_rating',
            name='create_user_mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='information_rating',
            name='upd_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='information_rating',
            name='upd_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='information_rating',
            name='upd_user_mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='create_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='upd_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='cert',
            name='create_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='gold',
            name='create_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='gold',
            name='upd_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='gold_cert_detail_price',
            name='create_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='gold_price_config',
            name='create_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='gold_price_config',
            name='upd_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='gold_promo',
            name='create_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='gold_promo',
            name='upd_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='information_promo',
            name='create_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='information_promo',
            name='upd_user',
            field=models.UUIDField(null=True),
        ),
    ]
