# Generated by Django 4.2.8 on 2025-03-16 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_rename_create_user_mail_bank_create_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold',
            name='certificate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cert'),
        ),
    ]
