# Generated by Django 4.2.8 on 2025-03-18 07:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_gold_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold',
            name='certificate_weight',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, null=True),
        ),
    ]
