# Generated by Django 4.2.8 on 2025-03-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_gold_certificate_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold',
            name='product_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
