# Generated by Django 4.2.8 on 2025-03-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_delivery_partner_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_method',
            fields=[
                ('payment_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method_name', models.CharField(max_length=50, unique=True)),
                ('payment_method_description', models.CharField(max_length=50, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
