# Generated by Django 4.2.8 on 2025-03-23 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_partner_service',
            name='delivery_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.delivery_partner'),
        ),
    ]
