# Generated by Django 4.2.8 on 2025-03-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_delivery_partner_service_delivery_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_partner',
            name='delivery_partner_code',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery_partner',
            name='delivery_partner_description',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
