# Generated by Django 4.2.8 on 2025-04-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_delivery_partner_delivery_partner_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold_cert_detail_price',
            name='fee_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
