# Generated by Django 4.2.8 on 2025-04-28 08:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_gold_cert_detail_price_fee_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold',
            name='certificate_weight',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='gold',
            name='product_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
