# Generated by Django 4.2.8 on 2025-04-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_gold_certificate_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_partner',
            name='delivery_partner_external',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='delivery_partner_service',
            name='delivery_partner_service_external',
            field=models.BooleanField(default=True),
        ),
    ]
