# Generated by Django 4.2.8 on 2025-04-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_delivery_partner_delivery_partner_external_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_method',
            name='payment_method_external',
            field=models.BooleanField(default=True),
        ),
    ]
