# Generated by Django 4.2.8 on 2025-05-07 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_gold_reedem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gold',
            old_name='reedem_price',
            new_name='redeem_price',
        ),
    ]
