# Generated by Django 4.2.8 on 2025-05-25 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_rename_reedem_price_gold_redeem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold_cert_detail_price',
            name='gold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_cert_detail_price', to='core.gold'),
        ),
    ]
