# Generated by Django 4.2.8 on 2025-06-02 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_gold_cert_detail_price_gold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cert',
            old_name='cert_name',
            new_name='cert_brand',
        ),
    ]
