# Generated by Django 4.2.8 on 2025-07-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_rename_cert_name_cert_cert_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fee_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percentage or fixed amount', max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentReturn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='ROI rate as a percentage (e.g., 5.00 for 5%)', max_digits=5)),
                ('duration_days', models.PositiveIntegerField(help_text='Duration for ROI calculation in days')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CeleryTasks',
        ),
    ]
