# Generated by Django 4.2.8 on 2025-07-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_adminfee_investmentreturn_delete_celerytasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminfee',
            name='transaction_type',
            field=models.CharField(choices=[('investment', 'Investment'), ('redeem', 'Redeem')], default='investment', max_length=20),
        ),
        migrations.AlterField(
            model_name='adminfee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
