# Generated by Django 4.2.8 on 2025-08-04 13:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0050_goldstock_goldloanhistory_goldhistory_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoldDepositoHistory',
            new_name='gold_deposito_history',
        ),
        migrations.RenameModel(
            old_name='GoldHistory',
            new_name='gold_history',
        ),
        migrations.RenameModel(
            old_name='GoldLoanHistory',
            new_name='gold_loan_history',
        ),
        migrations.RenameModel(
            old_name='GoldStock',
            new_name='gold_stock',
        ),
    ]
