# Generated by Django 4.2.8 on 2025-08-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_rename_golddepositohistory_gold_deposito_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gold_history',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gold_loan_history',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gold_stock',
            name='user',
        ),
        migrations.DeleteModel(
            name='gold_deposito_history',
        ),
        migrations.DeleteModel(
            name='gold_history',
        ),
        migrations.DeleteModel(
            name='gold_loan_history',
        ),
        migrations.DeleteModel(
            name='gold_stock',
        ),
    ]
