# Generated by Django 4.2.8 on 2025-02-03 16:21

import core.fields.uuidv7_field
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='topup_qris_webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('payment_id', models.CharField(max_length=255, unique=True)),
                ('business_id', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], max_length=20)),
                ('qr_id', models.CharField(max_length=255)),
                ('reference_id', models.CharField(max_length=255)),
                ('channel_code', models.CharField(max_length=50)),
                ('expires_at', models.DateTimeField()),
                ('metadata', models.JSONField(default=dict)),
                ('payment_detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='topup_va_webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255, unique=True)),
                ('account_number', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('external_id', models.CharField(max_length=255)),
                ('bank_code', models.CharField(max_length=50)),
                ('transaction_time', models.DateTimeField(null=True)),
                ('raw_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='withraw_transaction',
            fields=[
                ('topup_timestamp', models.DateTimeField(auto_created=True)),
                ('topup_transaction_id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('topup_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('topup_cost', models.DecimalField(decimal_places=2, max_digits=16)),
                ('topup_payment_method', models.CharField(max_length=255)),
                ('topup_payment_number', models.CharField(max_length=255)),
                ('topup_payment_ref', models.CharField(max_length=255)),
                ('topup_notes', models.TextField()),
                ('topup_status', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
