# Generated by Django 4.2.8 on 2025-02-15 14:02

import core.fields.uuidv7_field
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0002_topup_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='disburst_transaction',
            fields=[
                ('disburst_timestamp', models.DateTimeField(auto_created=True)),
                ('disburst_transaction_id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('disburst_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('disburst_admin', models.DecimalField(decimal_places=2, max_digits=16)),
                ('disburst_total_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('disburst_payment_bank', models.CharField(max_length=255)),
                ('disburst_payment_bank_number', models.CharField(max_length=255)),
                ('disburst_status', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
