# Generated by Django 4.2.8 on 2025-02-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_disburst_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disburst_transaction',
            old_name='disburst_payment_bank',
            new_name='disburst_payment_bank_account_holder_name',
        ),
        migrations.AddField(
            model_name='disburst_transaction',
            name='disburst_payment_bank_code',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disburst_transaction',
            name='disburst_payment_ref',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
