# Generated by Django 4.2.8 on 2025-05-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_rename_disburst_payment_bank_disburst_transaction_disburst_payment_bank_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topup_transaction',
            name='topup_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
