# Generated by Django 4.2.8 on 2025-05-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_topup_transaction_topup_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='disburst_transaction',
            name='disburst_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='withraw_transaction',
        ),
    ]
