# Generated by Django 4.2.8 on 2025-05-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_disburst_transaction_disburst_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='qris_webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('business_id', models.CharField(max_length=50)),
                ('data_id', models.CharField(max_length=100)),
                ('data_business_id', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=10)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=20)),
                ('data_created', models.DateTimeField()),
                ('qr_id', models.CharField(max_length=100)),
                ('qr_string', models.TextField()),
                ('reference_id', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('channel_code', models.CharField(max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('branch_code', models.CharField(max_length=100)),
                ('receipt_id', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='virtual_account_webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('callback_virtual_account_id', models.CharField(max_length=100)),
                ('owner_id', models.CharField(max_length=100)),
                ('external_id', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('bank_code', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('transaction_timestamp', models.DateTimeField()),
                ('merchant_code', models.CharField(max_length=50)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
        ),
    ]
