# Generated by Django 4.2.8 on 2025-07-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_qris_webhook_virtual_account_webhook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtual_account_webhook',
            name='payment_id',
            field=models.CharField(max_length=100),
        ),
    ]
