# Generated by Django 4.2.8 on 2025-07-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_alter_virtual_account_webhook_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qris_webhook',
            name='reference_id',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='virtual_account_webhook',
            name='external_id',
            field=models.CharField(max_length=1000),
        ),
    ]
