# Generated by Django 4.2.8 on 2025-07-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_alter_qris_webhook_reference_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qris_webhook',
            name='branch_code',
        ),
        migrations.RemoveField(
            model_name='qris_webhook',
            name='receipt_id',
        ),
        migrations.RemoveField(
            model_name='qris_webhook',
            name='source',
        ),
    ]
