# Generated by Django 4.2.8 on 2025-08-04 13:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0011_wallethistory_wallet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WalletHistory',
            new_name='wallet_history',
        ),
    ]
