# Generated by Django 4.2.8 on 2024-11-20 13:16

import core.fields.uuidv7_field
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('pin', models.CharField(max_length=6)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.CharField(max_length=255)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('update_user', models.CharField(max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
        migrations.CreateModel(
            name='user_props',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True)),
                ('id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('wallet_amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gold_wgt', models.DecimalField(decimal_places=4, max_digits=10)),
                ('invest_gold_wgt', models.DecimalField(decimal_places=4, max_digits=10)),
                ('loan_wgt', models.DecimalField(decimal_places=4, max_digits=10)),
                ('loan_amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('photo', models.CharField(max_length=255)),
                ('bank', models.CharField(max_length=255)),
                ('rek_number', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('level_id', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('address_post_code', models.CharField(max_length=255)),
                ('create_user', models.CharField(max_length=255)),
                ('update_user', models.CharField(max_length=255)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_props', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_ktp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ktp_nik', models.CharField(blank=True, max_length=255, null=True)),
                ('ktp_nama', models.CharField(blank=True, max_length=255, null=True)),
                ('ktp_birth_date', models.DateField(blank=True, null=True)),
                ('ktp_birth_place', models.CharField(blank=True, max_length=255, null=True)),
                ('ktp_address', models.CharField(blank=True, max_length=255, null=True)),
                ('ktp_district', models.CharField(blank=True, max_length=255, null=True)),
                ('ktp_sub_district', models.CharField(blank=True, max_length=255, null=True)),
                ('ktp_nh_no', models.CharField(blank=True, max_length=255, null=True)),
                ('ktp_religion', models.CharField(blank=True, max_length=255, null=True)),
                ('ktp_marital_status', models.CharField(blank=True, max_length=255, null=True)),
                ('ktp_job', models.CharField(blank=True, max_length=255, null=True)),
                ('ktp_citizen', models.CharField(blank=True, max_length=255, null=True)),
                ('ktp_photo', models.CharField(blank=True, max_length=255, null=True)),
                ('ktp_city_id', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.CharField(blank=True, max_length=255, null=True)),
                ('create_user', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id', 'email', 'user_name'], name='user_user_id_5c826d_idx'),
        ),
    ]
