# Generated by Django 4.2.8 on 2024-11-20 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_user',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_user',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user_ktp',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user_ktp',
            name='ktp_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user_ktp',
            name='ktp_birth_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_ktp',
            name='ktp_birth_place',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user_ktp',
            name='ktp_citizen',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user_ktp',
            name='ktp_city_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user_ktp',
            name='ktp_district',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user_ktp',
            name='ktp_job',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user_ktp',
            name='ktp_marital_status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user_ktp',
            name='ktp_nama',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user_ktp',
            name='ktp_nh_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user_ktp',
            name='ktp_nik',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user_ktp',
            name='ktp_photo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user_ktp',
            name='ktp_religion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user_ktp',
            name='ktp_sub_district',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user_props',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.city'),
        ),
        migrations.AlterField(
            model_name='user_props',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
