# Generated by Django 4.2.8 on 2024-12-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_ktp',
            old_name='ktp_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user_ktp',
            old_name='ktp_birth_place',
            new_name='adminitrative_village',
        ),
        migrations.RenameField(
            model_name='user_ktp',
            old_name='ktp_citizen',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='user_ktp',
            old_name='ktp_birth_date',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='user_ktp',
            old_name='ktp_city_id',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='user_ktp',
            old_name='ktp_district',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='user_ktp',
            old_name='ktp_job',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='user_ktp',
            old_name='ktp_marital_status',
            new_name='marital_status',
        ),
        migrations.RenameField(
            model_name='user_ktp',
            old_name='ktp_nama',
            new_name='nationality',
        ),
        migrations.RenameField(
            model_name='user_ktp',
            old_name='ktp_nh_no',
            new_name='nik',
        ),
        migrations.RenameField(
            model_name='user_ktp',
            old_name='ktp_nik',
            new_name='occupation',
        ),
        migrations.RenameField(
            model_name='user_ktp',
            old_name='ktp_photo',
            new_name='photo_url',
        ),
        migrations.RenameField(
            model_name='user_ktp',
            old_name='ktp_religion',
            new_name='place_of_birth',
        ),
        migrations.RenameField(
            model_name='user_ktp',
            old_name='ktp_sub_district',
            new_name='religion',
        ),
        migrations.AddField(
            model_name='user_ktp',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user_ktp',
            name='updated_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
