# Generated by Django 4.2.8 on 2024-12-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_ktp_address_user_ktp_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_ktp',
            name='reference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
