# Generated by Django 4.2.8 on 2024-12-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_ktp_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_ktp',
            name='blood_type',
            field=models.CharField(default='-', max_length=3),
        ),
    ]
