# Generated by Django 4.2.8 on 2024-12-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_ktp_blood_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_ktp',
            name='date_of_birth',
            field=models.CharField(max_length=12),
        ),
    ]
