# Generated by Django 4.2.8 on 2024-12-22 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_ktp_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_ktp',
            old_name='adminitrative_village',
            new_name='administrative_village',
        ),
    ]
