# Generated by Django 4.2.8 on 2025-01-12 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_user_reset_token_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verify_status',
            field=models.CharField(default='unverified', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='verify_updated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AlterField(
            model_name='user_reset_token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 10, 7, 32, 228378, tzinfo=datetime.timezone.utc)),
        ),
    ]
