# Generated by Django 4.2.8 on 2025-01-22 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_user_ktp_photo_url_user_photo_ktp_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_ktp_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_selfie_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_reset_token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 23, 5, 21, 1, 771387, tzinfo=datetime.timezone.utc)),
        ),
    ]
