# Generated by Django 4.2.8 on 2025-01-22 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_user_photo_ktp_url_alter_user_photo_selfie_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reset_token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 23, 5, 25, 50, 866410, tzinfo=datetime.timezone.utc)),
        ),
    ]
