# Generated by Django 4.2.8 on 2025-01-22 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_user_reset_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reset_token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 23, 5, 34, 21, 34016, tzinfo=datetime.timezone.utc)),
        ),
    ]
