# Generated by Django 4.2.8 on 2025-01-22 19:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_user_reset_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reset_token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 23, 19, 28, 2, 193581, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='user_virtual_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('va_number', models.CharField(max_length=255)),
                ('bank', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.CharField(max_length=255)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('updated_user', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
