# Generated by Django 4.2.8 on 2025-01-22 21:10

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_user_reset_token_expires_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_ktp',
            old_name='updated_time',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='user_ktp',
            old_name='updated_user',
            new_name='update_user',
        ),
        migrations.RenameField(
            model_name='user_virtual_account',
            old_name='updated_time',
            new_name='update_time',
        ),
        migrations.RemoveField(
            model_name='user_virtual_account',
            name='updated_user',
        ),
        migrations.AddField(
            model_name='user_virtual_account',
            name='create_user_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_virtual_account',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_virtual_account',
            name='merchant_code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_virtual_account',
            name='owner_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_virtual_account',
            name='update_user',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_virtual_account',
            name='update_user_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_reset_token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 23, 21, 8, 12, 972022, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user_virtual_account',
            name='bank',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_virtual_account',
            name='create_user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_virtual_account',
            name='va_number',
            field=models.CharField(max_length=50),
        ),
    ]
