# Generated by Django 4.2.8 on 2025-01-23 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_rename_updated_time_user_ktp_update_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reset_token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 24, 15, 39, 48, 374664, tzinfo=datetime.timezone.utc)),
        ),
    ]
