# Generated by Django 4.2.8 on 2025-01-23 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_user_reset_token_expires_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_ktp',
            old_name='update_time',
            new_name='updated_time',
        ),
        migrations.RenameField(
            model_name='user_ktp',
            old_name='update_user',
            new_name='updated_user',
        ),
        migrations.AlterField(
            model_name='user_reset_token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 24, 17, 13, 5, 754762, tzinfo=datetime.timezone.utc)),
        ),
    ]
