# Generated by Django 4.2.8 on 2025-01-25 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_rename_update_time_user_ktp_updated_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reset_token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 26, 12, 1, 4, 512951, tzinfo=datetime.timezone.utc)),
        ),
    ]
