# Generated by Django 4.2.8 on 2025-01-25 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_user_reset_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reset_token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 26, 12, 18, 5, 504483, tzinfo=datetime.timezone.utc)),
        ),
    ]
