# Generated by Django 4.2.8 on 2025-01-26 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_user_reset_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reset_token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 18, 7, 20, 382641, tzinfo=datetime.timezone.utc)),
        ),
    ]
