# Generated by Django 4.2.8 on 2025-01-27 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_user_reset_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reset_token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 9, 40, 6, 770405, tzinfo=datetime.timezone.utc)),
        ),
    ]
