# Generated by Django 4.2.8 on 2025-01-27 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_user_reset_token_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_virtual_account',
            name='owner_id',
        ),
        migrations.AlterField(
            model_name='user_reset_token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 10, 16, 45, 5372, tzinfo=datetime.timezone.utc)),
        ),
    ]
