# Generated by Django 4.2.8 on 2025-01-27 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_remove_user_virtual_account_owner_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reset_token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 10, 17, 56, 614993, tzinfo=datetime.timezone.utc)),
        ),
    ]
