# Generated by Django 4.2.8 on 2025-01-29 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_alter_user_reset_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reset_token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 30, 19, 7, 14, 631241, tzinfo=datetime.timezone.utc)),
        ),
    ]
