# Generated by Django 4.2.8 on 2025-01-30 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_alter_user_reset_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reset_token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 31, 4, 48, 5, 193713, tzinfo=datetime.timezone.utc)),
        ),
    ]
