# Generated by Django 4.2.8 on 2025-02-02 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_alter_user_reset_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reset_token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 3, 15, 18, 57, 892276, tzinfo=datetime.timezone.utc)),
        ),
    ]
