# Generated by Django 4.2.8 on 2025-02-03 16:21

import core.fields.uuidv7_field
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_alter_user_reset_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reset_token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 4, 16, 21, 5, 240046, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user_reset_token',
            name='token',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='user_wallet_history',
            fields=[
                ('id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('wallet_history_date', models.DateTimeField(auto_now_add=True)),
                ('wallet_history_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wallet_history_type', models.CharField(max_length=1)),
                ('wallet_history_notes', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_gold_history',
            fields=[
                ('id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('gold_purchase_date', models.DateTimeField(auto_now_add=True)),
                ('gold_weight', models.DecimalField(decimal_places=4, max_digits=10)),
                ('gold_history_price_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gold_history_price_buy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gold_history_price_sell', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gold_history_type', models.CharField(max_length=1)),
                ('gold_history_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('gold_history_note', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
