# Generated by Django 4.2.8 on 2025-02-03 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_alter_user_reset_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reset_token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 4, 17, 51, 12, 529779, tzinfo=datetime.timezone.utc)),
        ),
    ]
