# Generated by Django 4.2.8 on 2025-02-03 18:11

import core.fields.uuidv7_field
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_alter_user_reset_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reset_token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 4, 18, 11, 5, 64446, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='user_transfer_history',
            fields=[
                ('id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('trf_user_from_name', models.CharField(max_length=255)),
                ('trf_history_date', models.DateTimeField(auto_now_add=True)),
                ('trf_history_amount', models.DecimalField(decimal_places=4, max_digits=8)),
                ('trf_user_to_name', models.CharField(max_length=255)),
                ('trf_ref_number', models.CharField(max_length=255)),
                ('trf_history_notes', models.CharField(max_length=255)),
                ('trf_type', models.CharField(max_length=1)),
                ('trf_user_to_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
