# Generated by Django 4.2.8 on 2025-02-05 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_alter_user_reset_token_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reset_token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 18, 56, 50, 440450, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='user_transfer_history',
        ),
    ]
