# Generated by Django 4.2.8 on 2025-02-15 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_alter_user_reset_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reset_token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 16, 14, 2, 27, 754043, tzinfo=datetime.timezone.utc)),
        ),
    ]
