# Generated by Django 4.2.8 on 2025-02-16 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_alter_user_reset_token_expires_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_props',
            old_name='rek_number',
            new_name='bank_account_holder_name',
        ),
        migrations.AddField(
            model_name='user_props',
            name='bank_account_number',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_reset_token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 10, 42, 36, 875926, tzinfo=datetime.timezone.utc)),
        ),
    ]
