# Generated by Django 4.2.8 on 2025-02-16 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_rename_rek_number_user_props_bank_account_holder_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_props',
            old_name='bank',
            new_name='bank_account_code',
        ),
        migrations.AlterField(
            model_name='user_reset_token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 10, 52, 41, 511613, tzinfo=datetime.timezone.utc)),
        ),
    ]
