# Generated by Django 4.2.8 on 2025-03-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0055_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_props',
            name='income_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user_props',
            name='investation_purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user_props',
            name='referal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
