# Generated by Django 4.2.8 on 2025-03-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0056_user_props_income_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_props',
            old_name='investation_purpose',
            new_name='investment_purpose',
        ),
    ]
