# Generated by Django 4.2.8 on 2025-03-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0057_rename_investation_purpose_user_props_investment_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_address',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user_address',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
