# Generated by Django 4.2.8 on 2025-03-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0058_user_address_is_default_user_address_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='is_default',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
