# Generated by Django 4.2.8 on 2025-03-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0059_alter_user_address_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
