# Generated by Django 4.2.8 on 2025-03-30 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_delivery_partner_delivery_partner_code_and_more'),
        ('user', '0060_alter_user_address_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_virtual_account',
            name='bank_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_virtual_account',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bank'),
        ),
    ]
