# Generated by Django 4.2.8 on 2025-05-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0061_user_virtual_account_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_address',
            name='phone_number',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
