# Generated by Django 4.2.8 on 2025-05-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0063_user_member_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reset_token',
            name='type',
            field=models.CharField(choices=[('Password', 'Reset Password'), ('Pin', 'Reset PIN')], default='Password', max_length=100),
        ),
    ]
