# Generated by Django 4.2.8 on 2025-05-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0064_alter_user_reset_token_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reset_token',
            name='type',
            field=models.CharField(choices=[('reset_password', 'Reset Password'), ('reset_pin', 'Reset PIN')], default='Password', max_length=100),
        ),
    ]
