# Generated by Django 4.2.8 on 2025-06-21 02:04

import core.fields.uuidv7_field
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0065_alter_user_reset_token_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_notification',
            fields=[
                ('user_notification_id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_notification_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('user_notification_description', models.TextField(blank=True, null=True)),
                ('user_notification_date', models.DateTimeField(auto_now_add=True)),
                ('user_notification_icon_type', models.CharField(default='info', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
