# Generated by Django 4.2.8 on 2025-06-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0066_user_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_notification',
            name='user_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_notification',
            name='user_transaction_type',
            field=models.CharField(blank=True, choices=[('gold_buy', 'Buy'), ('gold_sell', 'Sell'), ('gold_transfer_send', 'Transfer Send'), ('gold_transfer_receive', 'Transfer Receive'), ('order_gold', 'Order Gold'), ('tarik_emas', 'Tarik Emas'), ('topup', 'Top Up'), ('withdraw', 'Withdraw'), ('forgot_password', 'Forgot Password')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_notification',
            name='user_notification_icon_type',
            field=models.CharField(choices=[('info', 'Info'), ('transaction', 'Transaction')], default='info', max_length=100),
        ),
    ]
