# Generated by Django 4.2.8 on 2025-06-23 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0068_user_notification_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_notification_price',
            old_name='user_notification_price_max',
            new_name='user_notification_price_buy',
        ),
        migrations.RenameField(
            model_name='user_notification_price',
            old_name='user_notification_price_min',
            new_name='user_notification_price_sell',
        ),
    ]
