# Generated by Django 4.2.8 on 2025-06-23 12:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0069_rename_user_notification_price_max_user_notification_price_user_notification_price_buy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_notification_price',
            name='user_notification_price_buy',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='user_notification_price',
            name='user_notification_price_sell',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
    ]
