# Generated by Django 4.2.8 on 2025-06-23 12:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0070_alter_user_notification_price_user_notification_price_buy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_notification_price',
            name='user_notification_price_buy',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='user_notification_price',
            name='user_notification_price_sell',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=16, null=True),
        ),
    ]
