# Generated by Django 4.2.8 on 2025-07-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0071_alter_user_notification_price_user_notification_price_buy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user_address',
            name='longtitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
