# Generated by Django 4.2.8 on 2025-07-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0072_user_address_latitude_user_address_longtitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_address',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
