# Generated by Django 4.2.8 on 2025-07-05 09:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0074_alter_user_address_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_props',
            name='total_buy',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='user_props',
            name='total_sell',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
    ]
