# Generated by Django 4.2.8 on 2025-07-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0075_user_props_total_buy_user_props_total_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_2fa_verified',
            field=models.BooleanField(default=False),
        ),
    ]
