# Generated by Django 4.2.8 on 2025-07-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0077_user_is_deleted_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_photo_selfie_verified',
            field=models.BooleanField(default=False),
        ),
    ]
