# Generated by Django 4.2.8 on 2025-07-24 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0078_user_is_photo_selfie_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='verify_status',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='user_notification',
            name='user_transaction_type',
            field=models.CharField(blank=True, choices=[('gold_buy', 'Buy'), ('gold_sell', 'Sell'), ('gold_transfer_send', 'Transfer Send'), ('gold_transfer_receive', 'Transfer Receive'), ('order_gold', 'Order Gold'), ('tarik_emas', 'Tarik Emas'), ('topup', 'Top Up'), ('withdraw', 'Withdraw'), ('forgot_password', 'Forgot Password'), ('email_verification', 'Email Verification')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('roles', models.ManyToManyField(related_name='menus', to='user.role')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.role'),
        ),
    ]
