# Generated by Django 4.2.8 on 2025-08-02 09:52

import core.fields.uuidv7_field
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0079_role_alter_user_verify_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldDepositoHistory',
            fields=[
                ('id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('price_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_sell', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('amount_dividend', models.DecimalField(decimal_places=2, max_digits=16)),
                ('weight', models.DecimalField(decimal_places=4, max_digits=10)),
                ('weight_dividend', models.DecimalField(decimal_places=2, max_digits=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gold Deposito History',
                'verbose_name_plural': 'Gold Deposito Histories',
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoldHistory',
            fields=[
                ('id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('weight', models.DecimalField(decimal_places=4, max_digits=10)),
                ('price_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_buy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_sell', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gold History',
                'verbose_name_plural': 'Gold Histories',
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoldLoanHistory',
            fields=[
                ('id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('price_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_sell', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('weight', models.DecimalField(decimal_places=4, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('admin_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gold Loan History',
                'verbose_name_plural': 'Gold Loan Histories',
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WalletHistory',
            fields=[
                ('id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('D', 'Deposit'), ('W', 'Withdrawal')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet History',
                'verbose_name_plural': 'Wallet Histories',
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='user_wallet_history',
            name='user',
        ),
        migrations.DeleteModel(
            name='user_gold_history',
        ),
        migrations.DeleteModel(
            name='user_wallet_history',
        ),
    ]
