# Generated by Django 4.2.8 on 2025-08-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0080_golddepositohistory_goldhistory_goldloanhistory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goldhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='goldloanhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wallethistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='GoldDepositoHistory',
        ),
        migrations.DeleteModel(
            name='GoldHistory',
        ),
        migrations.DeleteModel(
            name='GoldLoanHistory',
        ),
        migrations.DeleteModel(
            name='WalletHistory',
        ),
    ]
