# Generated by Django 4.2.8 on 2024-09-17 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ulid.models
import ulid.api.api


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('pin', models.CharField(max_length=6)),
                ('create_time', models.CharField(max_length=255)),
                ('create_user', models.CharField(max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
        migrations.CreateModel(
            name='user_props',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True)),
                ('id', django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False, unique=True)),
                ('wallet_amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gold_wgt', models.DecimalField(decimal_places=4, max_digits=10)),
                ('invest_gold_wgt', models.DecimalField(decimal_places=4, max_digits=10)),
                ('loan_wgt', models.DecimalField(decimal_places=4, max_digits=10)),
                ('loan_amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('photo', models.CharField(max_length=255)),
                ('bank', models.CharField(max_length=255)),
                ('rek_number', models.CharField(max_length=255)),
                ('npwp', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('address_post_code', models.CharField(max_length=255)),
                ('create_user', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_ktp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ktp_number', models.CharField(max_length=255)),
                ('ktp_photo', models.CharField(max_length=255)),
                ('ktp_address', models.CharField(max_length=255)),
                ('ktp_address_post_code', models.CharField(max_length=255)),
                ('ktp_city_id', models.CharField(max_length=255)),
                ('ktp_create_time', models.CharField(max_length=255)),
                ('ktp_create_user', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id', 'email'], name='user_user_id_f9b503_idx'),
        ),
    ]
