# Generated by Django 3.2.25 on 2024-08-28 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('pin', models.CharField(max_length=6)),
                ('wallet_amt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gold_wgt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('invest_gold_wgt', models.CharField(max_length=255)),
                ('loan_wgt', models.CharField(max_length=255)),
                ('loan_amt', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=255)),
                ('bank', models.CharField(max_length=255)),
                ('rek_number', models.CharField(max_length=255)),
                ('npwp', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('city_id', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('address_post_code', models.CharField(max_length=255)),
                ('create_time', models.CharField(max_length=255)),
                ('create_user', models.CharField(max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserKtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ktp_number', models.CharField(max_length=255)),
                ('ktp_photo', models.CharField(max_length=255)),
                ('ktp_address', models.CharField(max_length=255)),
                ('ktp_address_post_code', models.CharField(max_length=255)),
                ('ktp_city_id', models.CharField(max_length=255)),
                ('ktp_create_time', models.CharField(max_length=255)),
                ('ktp_create_user', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
