# Generated by Django 4.2.8 on 2024-09-17 12:35

from django.db import migrations
import django_ulid.models
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('gold_transaction', '0006_alter_gold_buy_gold_buy_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold_buy',
            name='gold_buy_id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gold_transaction',
            name='gold_transaction_id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gold_transfer',
            name='gold_transfer_id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user_gold_history',
            name='gold_buy_id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
