# Generated by Django 3.2.25 on 2024-08-28 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gold',
            fields=[
                ('gold_id', models.AutoField(primary_key=True, serialize=False)),
                ('gold_weight', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=255)),
                ('certificate_number', models.CharField(max_length=255)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('createuser', models.CharField(max_length=255)),
                ('updtime', models.DateTimeField(auto_now=True)),
                ('upduser', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GoldCertPrice',
            fields=[
                ('cert_id', models.AutoField(primary_key=True, serialize=False)),
                ('gold_weight', models.IntegerField()),
                ('cert_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('createuser', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GoldPrice',
            fields=[
                ('gold_price_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('gold_price_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gold_price_sell', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gold_price_buy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoldPriceSetting',
            fields=[
                ('gps_id', models.AutoField(primary_key=True, serialize=False)),
                ('weekend_price_buy', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weekend_price_sell', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weekday_price_sell', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weekday_price_buy_add_cost1', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weekday_price_buy_add_cost2', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weekday_price_buy_add_cost3', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(max_length=50)),
                ('updtime', models.DateTimeField(auto_now=True)),
                ('upduser', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InformationCustomerService',
            fields=[
                ('information_customer_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('information_phone', models.CharField(max_length=20)),
                ('information_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InformationEducational',
            fields=[
                ('information_educational_id', models.AutoField(primary_key=True, serialize=False)),
                ('information_name', models.CharField(max_length=255)),
                ('information_notes', models.TextField(blank=True, null=True)),
                ('information_url', models.URLField(blank=True, null=True)),
                ('information_background', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InformationPromo',
            fields=[
                ('id_promo', models.AutoField(primary_key=True, serialize=False)),
                ('promo_code', models.CharField(max_length=255)),
                ('leveling_user', models.CharField(max_length=50)),
                ('promo_name', models.CharField(max_length=255)),
                ('promo_url', models.CharField(max_length=255)),
                ('promo_start_date', models.DateTimeField()),
                ('promo_end_date', models.DateTimeField()),
                ('promo_tag', models.CharField(max_length=255)),
                ('promo_url_background', models.CharField(max_length=255)),
                ('promo_diskon', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('promo_cashback', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('promo_cashback_tipe_user', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant_cashback', models.CharField(blank=True, max_length=255, null=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('createuser', models.CharField(max_length=255)),
                ('updtime', models.DateTimeField(auto_now=True)),
                ('upduser', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InformationRating',
            fields=[
                ('information_rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('information_rate_name', models.CharField(max_length=255)),
                ('rate', models.IntegerField()),
                ('message', models.TextField(blank=True, null=True)),
                ('publish', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.AutoField(primary_key=True, serialize=False)),
                ('province_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=255)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.province')),
            ],
        ),
    ]
