# Generated by Django 4.2.8 on 2024-09-17 01:18

from django.db import migrations, models
import django_ulid.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gold_price_rate',
            fields=[
                ('gold_price_rate_id', django_ulid.models.ULIDField(primary_key=True, serialize=False)),
                ('gold_price_rate_source', models.CharField(max_length=255)),
                ('gold_price_rate_weight', models.IntegerField()),
                ('gold_price_rate_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gold_price_timestamps', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='information_faq',
            fields=[
                ('information_faq_id', models.AutoField(primary_key=True, serialize=False)),
                ('information_title', models.CharField(max_length=255)),
                ('information_question', models.TextField(blank=True, null=True)),
                ('information_answer', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
