# Generated by Django 4.2.8 on 2024-09-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gold_price_source_gold_cert_price_cert_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gold_price_config',
            old_name='gold_price_setting_model',
            new_name='gold_price_setting_model_buy_weekday',
        ),
        migrations.AddField(
            model_name='gold_price_config',
            name='gold_price_setting_model_buy_weekend',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gold_price_config',
            name='gold_price_setting_model_sell_weekday',
            field=models.CharField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gold_price_config',
            name='gold_price_setting_model_sell_weekend',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
