# Generated by Django 4.2.8 on 2024-09-17 12:35

from django.db import migrations, models
import django_ulid.models
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_gold_price_rate_gold_price_rate_base_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gold_price_rate',
        ),
        migrations.AddField(
            model_name='gold_price',
            name='gold_price_setting_source',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='gold_price',
            name='gold_price_setting_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gold_price',
            name='gold_price_id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
