# Generated by Django 4.2.8 on 2024-10-05 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_gold_price_setting_model_gold_price_config_gold_price_setting_model_buy_weekday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='district',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city')),
            ],
        ),
        migrations.CreateModel(
            name='sub_district',
            fields=[
                ('subdistrict_id', models.AutoField(primary_key=True, serialize=False)),
                ('subdistrict_name', models.CharField(max_length=255)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.district')),
            ],
        ),
        migrations.CreateModel(
            name='sub_district_post_code',
            fields=[
                ('post_code_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_code', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.district')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.province')),
                ('subdistrict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sub_district')),
            ],
        ),
    ]
