# Generated by Django 4.2.8 on 2024-10-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_district_sub_district_sub_district_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='district',
            name='district_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='province',
            name='province_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sub_district',
            name='subdistrict_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sub_district_post_code',
            name='post_code_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
