# Generated by Django 4.2.8 on 2024-10-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_post_code_id_postal_code_postal_code_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sub_district',
            new_name='subdistrict',
        ),
    ]
