# Generated by Django 4.2.8 on 2024-11-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_sub_district_subdistrict'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_promo',
            fields=[
                ('order_promo_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_promo_code', models.CharField(max_length=50)),
                ('order_promo_description', models.CharField(max_length=255)),
                ('order_promo_weight', models.DecimalField(decimal_places=4, max_digits=8)),
                ('order_promo_amt_pct', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_promo_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_promo_min_weight', models.DecimalField(decimal_places=4, max_digits=8)),
                ('order_promo_max_weight', models.DecimalField(decimal_places=4, max_digits=8)),
                ('order_promo_min_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_promo_max_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_promo_start_date', models.DateField()),
                ('order_promo_end_date', models.DateField()),
                ('order_promo_active', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.CharField(max_length=255)),
                ('upd_time', models.DateTimeField(auto_now=True)),
                ('upd_user', models.CharField(max_length=255)),
            ],
        ),
    ]
