# Generated by Django 4.2.8 on 2025-01-22 05:26

import core.fields.uuidv7_field
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='withraw_transaction',
            fields=[
                ('topup_timestamp', models.DateTimeField(auto_created=True)),
                ('topup_transaction_id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('topup_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('topup_cost', models.DecimalField(decimal_places=2, max_digits=16)),
                ('topup_payment_method', models.CharField(max_length=255)),
                ('topup_payment_number', models.CharField(max_length=255)),
                ('topup_payment_ref', models.CharField(max_length=255)),
                ('topup_notes', models.TextField()),
                ('topup_status', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='topup_transaction',
            fields=[
                ('topup_timestamp', models.DateTimeField(auto_created=True)),
                ('topup_transaction_id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('topup_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('topup_cost', models.DecimalField(decimal_places=2, max_digits=16)),
                ('topup_payment_method', models.CharField(max_length=255)),
                ('topup_payment_number', models.CharField(max_length=255)),
                ('topup_payment_ref', models.CharField(max_length=255)),
                ('topup_notes', models.TextField()),
                ('topup_status', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
