# Generated by Django 4.2.8 on 2025-01-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topup_transaction',
            old_name='topup_cost',
            new_name='topup_admin',
        ),
        migrations.AddField(
            model_name='topup_transaction',
            name='topup_payment_bank',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
