# Generated by Django 4.2.8 on 2025-01-22 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0002_rename_topup_cost_topup_transaction_topup_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topup_transaction',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topup_transaction',
            name='create_user',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topup_transaction',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='topup_transaction',
            name='update_user',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topup_transaction',
            name='update_user_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
