# Generated by Django 4.2.8 on 2025-01-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0003_topup_transaction_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topup_transaction',
            name='topup_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
    ]
