# Generated by Django 4.2.8 on 2025-01-25 12:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_bank_bank_va_range_end_bank_bank_va_range_start'),
        ('ewallet', '0005_alter_topup_transaction_topup_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topup_transaction',
            old_name='create_user',
            new_name='topup_payment_ref_code',
        ),
        migrations.AddField(
            model_name='topup_transaction',
            name='topup_payment_channel_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='topup_transaction',
            name='topup_payment_expired_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topup_transaction',
            name='topup_notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='topup_transaction',
            name='topup_payment_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bank'),
        ),
        migrations.AlterField(
            model_name='topup_transaction',
            name='topup_status',
            field=models.CharField(default='PENDING', max_length=255),
        ),
    ]
