# Generated by Django 4.2.8 on 2025-01-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0006_rename_create_user_topup_transaction_topup_payment_ref_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topup_transaction',
            old_name='topup_payment_expired_at',
            new_name='topup_payment_expires_at',
        ),
    ]
