# Generated by Django 4.2.8 on 2025-01-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0007_rename_topup_payment_expired_at_topup_transaction_topup_payment_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='topup_transaction',
            name='topup_payment_bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
