from .informations_customer_service_view import InformationCustomerServiceViewSet
from .informations_educational_view import InformationEducationViewSet
from .informations_promo_view import InformationPromoViewSet, PromoUploadAPIView
from .informations_rating_view import InformationRatingViewSet
from .informations_article_view import InformationArticleViewSet
