# Generated by Django 4.2.8 on 2025-02-18 16:37

import core.fields.uuidv7_field
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0014_bank_bank_create_code_va_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='order_cart',
            fields=[
                ('updated_at', models.DateTimeField(auto_created=True)),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('order_cart_id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order_gold',
            fields=[
                ('tracking_sla', models.DateTimeField(auto_created=True)),
                ('tracking_last_updated_datetime', models.DateTimeField(auto_created=True)),
                ('order_timestamp', models.DateTimeField(auto_created=True)),
                ('order_gold_id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('order_number', models.CharField(max_length=255)),
                ('order_address', models.CharField(max_length=255)),
                ('order_postal_code', models.CharField(max_length=255)),
                ('order_phone_number', models.CharField(max_length=255)),
                ('order_item_weight', models.DecimalField(decimal_places=4, max_digits=10)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('order_tracking_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_promo_code', models.CharField(max_length=255)),
                ('order_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_total_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('tracking_status_id', models.CharField(max_length=255)),
                ('tracking_status', models.CharField(max_length=255)),
                ('tracking_courier', models.CharField(max_length=255)),
                ('tracking_number', models.CharField(max_length=255)),
                ('tracking_last_note', models.CharField(max_length=255)),
                ('order_post_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.postal_code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order_gold_detail',
            fields=[
                ('order_gold_detail_id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('gold_type', models.CharField(max_length=255)),
                ('gold_brand', models.CharField(max_length=255)),
                ('certificate_number', models.CharField(max_length=255)),
                ('order_qty', models.IntegerField()),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('order_cert_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_detail_total_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('cert_price_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gold_cert_price')),
                ('gold_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gold')),
                ('gold_price_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gold_price_config')),
                ('order_gold_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order_gold')),
            ],
        ),
        migrations.CreateModel(
            name='order_cart_detail',
            fields=[
                ('updated_at', models.DateTimeField(auto_created=True)),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('order_gold_detail_id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantitiy', models.IntegerField()),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order_cart')),
                ('gold_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gold')),
            ],
            options={
                'unique_together': {('cart_id', 'gold_id')},
            },
        ),
    ]
