# Generated by Django 4.2.8 on 2025-02-18 20:08

import core.fields.uuidv7_field
from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delivery_partner'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_tracking',
            fields=[
                ('tracking_timestamp', models.DateTimeField(auto_created=True)),
                ('order_tracking_id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tracking_number', models.CharField(max_length=50)),
                ('tracking_status', models.CharField(max_length=50)),
                ('tracking_notes', models.CharField(max_length=100)),
                ('order_gold_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order_gold')),
            ],
        ),
        migrations.CreateModel(
            name='order_shipping',
            fields=[
                ('delivery_actual_date', models.DateTimeField(auto_created=True)),
                ('delivery_est_date', models.DateTimeField(auto_created=True)),
                ('delivery_pickup_date', models.DateTimeField(auto_created=True)),
                ('delivery_pickup_order_date', models.DateTimeField(auto_created=True)),
                ('order_delivery_id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('delivery_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('delivery_insurance_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('delivery_total_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('delivery_partner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.delivery_partner')),
                ('order_gold_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order_gold')),
            ],
        ),
        migrations.CreateModel(
            name='order_payment',
            fields=[
                ('order_payment_timestamp', models.DateTimeField(auto_created=True)),
                ('order_payment_bill_id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('order_payment_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('order_payment_external_id', models.CharField(max_length=255)),
                ('order_payment_number', models.CharField(max_length=255)),
                ('order_payment_ref', models.CharField(max_length=255)),
                ('order_payment_status', models.CharField(max_length=255)),
                ('order_gold_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order_gold')),
            ],
        ),
    ]
