# Generated by Django 4.2.8 on 2025-02-19 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_cart_detail_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_cart',
            name='cart_status',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_cart',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_cart',
            name='total_weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
