# Generated by Django 4.2.8 on 2025-02-20 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0004_order_cart_cart_status_order_cart_total_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_cart',
            old_name='total_amount',
            new_name='total_price',
        ),
        migrations.RenameField(
            model_name='order_cart_detail',
            old_name='order_gold_detail_id',
            new_name='order_cart_detail_id',
        ),
        migrations.RemoveField(
            model_name='order_cart_detail',
            name='quantitiy',
        ),
        migrations.AddField(
            model_name='order_cart_detail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_cart_detail',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order_cart_detail',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order_cart_detail',
            name='weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
