# Generated by Django 4.2.8 on 2025-02-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_rename_total_amount_order_cart_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_cart_detail',
            name='session_key',
        ),
        migrations.AddField(
            model_name='order_cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order_cart_detail',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
