# Generated by Django 4.2.8 on 2025-02-24 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_cart_detail_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_cart_detail',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order_cart_detail',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
