# Generated by Django 4.2.8 on 2025-02-24 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_cart_detail_selected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_cart',
            name='cart_status',
        ),
    ]
