# Generated by Django 4.2.8 on 2025-02-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_order_cart_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_cart_detail',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16),
            preserve_default=False,
        ),
    ]
