# Generated by Django 4.2.8 on 2025-02-26 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0055_user_address'),
        ('order', '0009_order_cart_detail_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_gold',
            name='order_address',
        ),
        migrations.AddField(
            model_name='order_gold',
            name='order_user_address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.user_address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order_gold',
            name='tracking_courier',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order_gold',
            name='tracking_last_note',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order_gold',
            name='tracking_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order_gold',
            name='tracking_status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order_gold',
            name='tracking_status_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
