# Generated by Django 4.2.8 on 2025-02-27 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_rename_order_postal_code_order_gold_order_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_gold_detail',
            old_name='gold_id',
            new_name='gold',
        ),
    ]
