# Generated by Django 4.2.8 on 2025-02-27 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_gold_order_pickup_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_gold',
            name='order_pickup_customer_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
