# Generated by Django 4.2.8 on 2025-02-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_order_gold_order_pickup_customer_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_gold',
            name='order_payment_va_bank',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order_gold',
            name='order_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order_gold',
            name='order_pickup_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order_gold',
            name='order_pickup_customer_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_gold',
            name='order_promo_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order_gold',
            name='order_tracking_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order_gold',
            name='order_tracking_insurance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order_gold',
            name='order_tracking_insurance_admin',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order_gold',
            name='order_tracking_packing',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order_gold',
            name='order_tracking_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
