# Generated by Django 4.2.8 on 2025-02-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_order_gold_order_payment_va_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_gold',
            name='order_payment_va_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
