# Generated by Django 4.2.8 on 2025-03-12 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_cert_gold_cert_detail_price'),
        ('order', '0019_rename_order_gold_id_order_gold_detail_order_gold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_gold_detail',
            name='certificate_number',
        ),
        migrations.AlterField(
            model_name='order_gold_detail',
            name='cert_price_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cert'),
        ),
    ]
