# Generated by Django 4.2.8 on 2025-03-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_rename_order_gold_id_order_gold_detail_order_gold'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_gold',
            name='order_gold_payment_ref',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
