# Generated by Django 4.2.8 on 2025-03-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_order_gold_order_gold_payment_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_gold',
            name='order_gold_payment_status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
