# Generated by Django 4.2.8 on 2025-03-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_order_gold_order_gold_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_cart',
            name='completed_cart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_cart_detail',
            name='completed_cart',
            field=models.BooleanField(default=False),
        ),
    ]
