# Generated by Django 4.2.8 on 2025-03-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_remove_order_gold_detail_certificate_number_and_more'),
        ('order', '0022_order_cart_completed_cart_and_more'),
    ]

    operations = [
    ]
