# Generated by Django 4.2.8 on 2025-03-16 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_gold_certificate'),
        ('order', '0023_merge_20250314_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_cart_detail',
            name='cert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cert'),
        ),
        migrations.AlterField(
            model_name='order_cart_detail',
            name='selected',
            field=models.BooleanField(default=True),
        ),
    ]
