# Generated by Django 4.2.8 on 2025-03-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_order_cart_detail_cert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_cart_detail',
            name='cert_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
