# Generated by Django 4.2.8 on 2025-03-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_order_cart_detail_cert_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_cart_detail',
            name='product_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
