# Generated by Django 4.2.8 on 2025-03-19 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_rename_user_id_order_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_gold_detail',
            old_name='cert_price_id',
            new_name='cert',
        ),
        migrations.RenameField(
            model_name='order_gold_detail',
            old_name='gold_price_id',
            new_name='gold_price',
        ),
        migrations.AddField(
            model_name='order_gold',
            name='order_cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order_cart'),
        ),
        migrations.AddField(
            model_name='order_gold_detail',
            name='cert_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_gold_detail',
            name='order_cart_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order_cart_detail'),
        ),
        migrations.AddField(
            model_name='order_gold_detail',
            name='product_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
