# Generated by Django 4.2.8 on 2025-03-19 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_gold_gold_weight'),
        ('order', '0029_rename_cert_price_id_order_gold_detail_cert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_gold',
            name='tracking_courier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.delivery_partner'),
        ),
    ]
