# Generated by Django 4.2.8 on 2025-03-19 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_payment_method'),
        ('order', '0030_alter_order_gold_tracking_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_gold',
            name='tracking_courier_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.delivery_partner_service'),
        ),
    ]
