# Generated by Django 4.2.8 on 2025-03-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_order_payment_order_payment_admin_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_gold',
            name='tracking_courier_service_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
