# Generated by Django 4.2.8 on 2025-03-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_order_gold_tracking_courier_service_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_gold',
            name='order_payment_method_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order_gold',
            name='order_status',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
