# Generated by Django 4.2.8 on 2025-03-23 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_order_gold_order_payment_method_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_gold_detail',
            old_name='order_qty',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='order_gold_detail',
            old_name='order_weight',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='order_gold_detail',
            name='order_cert_price',
        ),
    ]
