# Generated by Django 4.2.8 on 2025-03-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_rename_order_qty_order_gold_detail_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_payment',
            name='order_payment_external_id',
        ),
        migrations.AlterField(
            model_name='order_payment',
            name='order_payment_number',
            field=models.CharField(max_length=2000),
        ),
    ]
