# Generated by Django 4.2.8 on 2025-03-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_remove_order_payment_order_payment_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_payment',
            name='order_payment_method_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
