# Generated by Django 4.2.8 on 2025-03-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_order_payment_order_payment_method_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_gold',
            name='order_rounded_total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16),
            preserve_default=False,
        ),
    ]
