# Generated by Django 4.2.8 on 2025-03-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0039_order_gold_order_rounded_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_gold',
            old_name='order_tracking_total',
            new_name='order_tracking_total_amount',
        ),
    ]
