# Generated by Django 4.2.8 on 2025-03-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0040_rename_order_tracking_total_order_gold_order_tracking_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_gold',
            name='order_tracking_total_amount_rounded',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
