# Generated by Django 4.2.8 on 2025-03-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0041_order_gold_order_tracking_total_amount_rounded"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order_cart_detail",
            old_name="cart_id",
            new_name="cart",
        ),
        migrations.AddField(
            model_name="order_cart_detail",
            name="total_price_round",
            field=models.DecimalField(
                decimal_places=0, default=0, editable=False, max_digits=16
            ),
            preserve_default=False,
        ),
    ]
