# Generated by Django 4.2.8 on 2025-03-31 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0042_rename_cart_id_order_cart_detail_cart'),
        ('order', '0042_rename_cart_id_order_cart_detail_cart_and_more'),
    ]

    operations = [
    ]
