# Generated by Django 4.2.8 on 2025-03-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0043_merge_20250331_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_gold',
            name='order_tracking_total_amount_rounded',
        ),
        migrations.AddField(
            model_name='order_gold',
            name='order_tracking_insurance_round',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order_gold',
            name='order_tracking_insurance_total',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
