# Generated by Django 4.2.8 on 2025-04-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0044_remove_order_gold_order_tracking_total_amount_rounded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_gold',
            name='order_rounded_total_price',
        ),
        migrations.AddField(
            model_name='order_cart',
            name='total_price_round',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_gold',
            name='order_total_price_round',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_gold_detail',
            name='order_detail_total_price_round',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16),
            preserve_default=False,
        ),
    ]
