# Generated by Django 4.2.8 on 2025-04-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0045_remove_order_gold_order_rounded_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_payment',
            name='order_payment_summary_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_payment',
            name='order_payment_summary_amount_round',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16),
            preserve_default=False,
        ),
    ]
