# Generated by Django 4.2.8 on 2025-04-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0046_order_payment_order_payment_summary_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_gold_detail',
            name='order_detail_status',
            field=models.CharField(default='open', max_length=255, null=True),
        ),
    ]
