# Generated by Django 4.2.8 on 2025-04-12 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0047_order_gold_detail_order_detail_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_gold_detail',
            old_name='order_detail_status',
            new_name='order_detail_stock_status',
        ),
    ]
