# Generated by Django 4.2.8 on 2025-04-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0048_rename_order_detail_status_order_gold_detail_order_detail_stock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_gold',
            name='order_pph22',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
