# Generated by Django 4.2.8 on 2025-04-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0049_order_gold_order_pph22'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_gold',
            name='order_grand_total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
    ]
