# Generated by Django 4.2.8 on 2025-04-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0050_order_gold_order_grand_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_cart_detail',
            name='gold_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order_gold_detail',
            name='gold_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
    ]
