# Generated by Django 4.2.8 on 2025-04-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0051_order_cart_detail_gold_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_shipping',
            name='delivery_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order_shipping',
            name='delivery_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order_shipping',
            name='delivery_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order_shipping',
            name='delivery_notes',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order_shipping',
            name='delivery_phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order_shipping',
            name='delivery_postal_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order_shipping',
            name='delivery_state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order_shipping',
            name='delivery_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order_shipping',
            name='delivery_tracking_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order_shipping',
            name='delivery_tracking_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
