# Generated by Django 4.2.8 on 2025-05-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0053_order_shipping_delivery_destination_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_cart',
            name='order_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order_cart',
            name='total_digital_admin_settlement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='order_cart',
            name='total_digital_admin_settlement_round',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='order_cart_detail',
            name='digital_admin_settlement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='order_cart_detail',
            name='digital_admin_settlement_round',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='order_cart_detail',
            name='order_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
