# Generated by Django 4.2.8 on 2025-05-07 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0055_rename_total_digital_admin_settlement_order_cart_order_summary_redeem_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_cart',
            old_name='order_summary_redeem_price',
            new_name='total_redeem_price',
        ),
        migrations.RenameField(
            model_name='order_cart_detail',
            old_name='order_detail_redeem_price',
            new_name='redeem_price',
        ),
        migrations.RemoveField(
            model_name='order_cart_detail',
            name='order_total_detail_redeem_price',
        ),
    ]
