# Generated by Django 4.2.8 on 2025-05-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0056_rename_order_summary_redeem_price_order_cart_total_redeem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_gold',
            name='order_shiping_item_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
