# Generated by Django 4.2.8 on 2025-05-08 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_rename_reedem_price_gold_redeem_price'),
        ('order', '0058_rename_order_shiping_item_amount_order_gold_order_shipping_item_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_cart_detail',
            name='gold_price_round',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_cart_detail',
            name='order_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_cart_detail',
            name='order_price_round',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_gold',
            name='order_pph22_round',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order_gold_detail',
            name='gold_price_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gold_price_config'),
        ),
        migrations.AddField(
            model_name='order_gold_detail',
            name='gold_price_round',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='order_gold_detail',
            name='order_price_round',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='order_gold_detail',
            name='gold_price',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='order_gold_detail',
            name='order_price',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
    ]
