# Generated by Django 4.2.8 on 2025-05-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0059_order_cart_detail_gold_price_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_gold',
            name='order_tracking_total_amount_rounded',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
