# Generated by Django 4.2.8 on 2025-05-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0061_remove_order_gold_order_pph22_round_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_gold',
            name='order_tracking_total_amount_rounded',
        ),
    ]
