# Generated by Django 4.2.8 on 2025-05-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0062_remove_order_gold_order_tracking_total_amount_rounded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_cart_detail',
            old_name='gold_price',
            new_name='item_price',
        ),
        migrations.RenameField(
            model_name='order_cart_detail',
            old_name='gold_price_round',
            new_name='item_price_round',
        ),
    ]
