# Generated by Django 4.2.8 on 2025-05-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0063_rename_gold_price_order_cart_detail_item_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_cart_detail',
            old_name='item_price',
            new_name='gold_price',
        ),
        migrations.RenameField(
            model_name='order_cart_detail',
            old_name='item_price_round',
            new_name='gold_price_round',
        ),
    ]
