# Generated by Django 4.2.8 on 2025-05-25 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_gold_cert_detail_price_gold'),
        ('order', '0064_rename_item_price_order_cart_detail_gold_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_gold_detail',
            name='gold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_gold_detail', to='core.gold'),
        ),
    ]
