# Generated by Django 4.2.8 on 2025-05-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0065_alter_order_gold_detail_gold'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_gold',
            name='order_tracking_insurance_total_round',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order_gold',
            name='order_tracking_total_amount_round',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
