# Generated by Django 4.2.8 on 2025-06-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0066_order_gold_order_tracking_insurance_total_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_gold_detail',
            name='cert_brand',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order_gold_detail',
            name='cert_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
