# Generated by Django 4.2.8 on 2025-06-02 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_rename_cert_name_cert_cert_brand'),
        ('order', '0067_order_gold_detail_cert_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_cart_detail',
            name='cert',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='core.cert'),
            preserve_default=False,
        ),
    ]
