# Generated by Django 4.2.8 on 2025-07-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0068_alter_order_cart_detail_cert'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_gold',
            name='gold_history_price_buy',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='order_gold',
            name='gold_history_price_sell',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
    ]
