# Generated by Django 4.2.8 on 2024-09-21 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gold_transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold_transfer',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_transfers_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gold_transfer',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_transfers_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
