# Generated by Django 4.2.8 on 2024-11-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold_transaction', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gold_buy',
        ),
        migrations.DeleteModel(
            name='gold_transaction',
        ),
        migrations.RemoveField(
            model_name='gold_transfer',
            name='user_from',
        ),
        migrations.RemoveField(
            model_name='gold_transfer',
            name='user_to',
        ),
        migrations.DeleteModel(
            name='user_gold_history',
        ),
        migrations.DeleteModel(
            name='gold_transfer',
        ),
    ]
