# Generated by Django 4.2.8 on 2025-01-22 05:34

import core.fields.uuidv7_field
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_rename_certificate_code_gold_certificate_number'),
        ('gold_transaction', '0003_delete_gold_buy_delete_gold_transaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='gold_buy',
            fields=[
                ('gold_buy_id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='gold_transaction',
            fields=[
                ('gold_transaction_id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='order_gold',
            fields=[
                ('tracking_sla', models.DateTimeField(auto_created=True)),
                ('tracking_last_updated_datetime', models.DateTimeField(auto_created=True)),
                ('order_timestamp', models.DateTimeField(auto_created=True)),
                ('order_gold_id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('order_number', models.CharField(max_length=255)),
                ('order_address', models.CharField(max_length=255)),
                ('order_postal_code', models.CharField(max_length=255)),
                ('order_phone_number', models.CharField(max_length=255)),
                ('order_item_weight', models.DecimalField(decimal_places=4, max_digits=10)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('order_tracking_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_promo_code', models.CharField(max_length=255)),
                ('order_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_total_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('tracking_status_id', models.CharField(max_length=255)),
                ('tracking_status', models.CharField(max_length=255)),
                ('tracking_courier', models.CharField(max_length=255)),
                ('tracking_number', models.CharField(max_length=255)),
                ('tracking_last_note', models.CharField(max_length=255)),
                ('order_post_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.postal_code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_gold_history',
            fields=[
                ('user_gold_hitory_id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='order_gold_detail',
            fields=[
                ('order_gold_detail_id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('gold_type', models.CharField(max_length=255)),
                ('gold_brand', models.CharField(max_length=255)),
                ('certificate_number', models.CharField(max_length=255)),
                ('order_qty', models.IntegerField()),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('order_cert_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_detail_total_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('cert_price_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gold_cert_price')),
                ('gold_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gold')),
                ('gold_price_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gold_price_config')),
                ('order_gold_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold_transaction.order_gold')),
            ],
        ),
        migrations.CreateModel(
            name='gold_transfer',
            fields=[
                ('transfer_member_datetime', models.DateTimeField(auto_created=True)),
                ('gold_transfer_id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('transfer_ref_number', models.CharField(max_length=255)),
                ('transfer_member_gold_weight', models.DecimalField(decimal_places=4, max_digits=8)),
                ('transfer_member_notes', models.TextField()),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_transfers_from', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_transfers_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
