# Generated by Django 4.2.8 on 2025-01-30 04:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_transaction', '0005_gold_transaction_price_per_gram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold_transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='gold_transaction',
            name='price_per_gram',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='gold_transaction',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
    ]
