# Generated by Django 4.2.8 on 2025-02-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_transaction', '0006_gold_transaction_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gold_transaction',
            old_name='purchase_date',
            new_name='transaction_date',
        ),
        migrations.AddField(
            model_name='gold_transaction',
            name='transaction_type',
            field=models.CharField(default='N', max_length=1),
            preserve_default=False,
        ),
    ]
