# Generated by Django 4.2.8 on 2025-02-03 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gold_transaction', '0008_gold_saving_buy_gold_saving_sell_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold_transfer',
            name='user_from_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gold_transfer',
            name='user_to_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
