# Generated by Django 4.2.8 on 2025-02-05 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gold_transaction', '0009_gold_transfer_user_from_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold_saving_sell',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
