# Generated by Django 4.2.8 on 2025-02-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold_transaction', '0010_alter_gold_saving_sell_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_gold_history',
        ),
    ]
