# Generated by Django 4.2.8 on 2025-02-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_transaction', '0012_alter_gold_saving_sell_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold_transfer',
            name='phone_number',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
