# Generated by Django 4.2.8 on 2025-02-18 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold_transaction', '0013_gold_transfer_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gold_buy',
        ),
        migrations.RemoveField(
            model_name='order_gold_detail',
            name='cert_price_id',
        ),
        migrations.RemoveField(
            model_name='order_gold_detail',
            name='gold_id',
        ),
        migrations.RemoveField(
            model_name='order_gold_detail',
            name='gold_price_id',
        ),
        migrations.RemoveField(
            model_name='order_gold_detail',
            name='order_gold_id',
        ),
        migrations.DeleteModel(
            name='order_gold',
        ),
        migrations.DeleteModel(
            name='order_gold_detail',
        ),
    ]
