# Generated by Django 4.2.8 on 2025-05-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_transaction', '0014_delete_gold_buy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold_saving_buy',
            name='gold_buy_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gold_saving_sell',
            name='gold_sell_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gold_transfer',
            name='gold_transfer_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
