# Generated by Django 4.2.8 on 2025-05-17 11:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_transaction', '0015_gold_saving_buy_gold_buy_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold_transfer',
            name='tranfer_member_service_option',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gold_transfer',
            name='transfer_member_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
    ]
