# Generated by Django 4.2.8 on 2025-05-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold_transaction', '0016_gold_transfer_tranfer_member_service_option_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gold_transfer',
            old_name='tranfer_member_service_option',
            new_name='transfer_member_service_option',
        ),
    ]
