# Generated by Django 4.2.8 on 2025-05-19 13:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_transaction', '0017_rename_tranfer_member_service_option_gold_transfer_transfer_member_service_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold_transfer',
            name='transfer_member_admin_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.AddField(
            model_name='gold_transfer',
            name='transfer_member_admin_weight',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8),
        ),
    ]
