# Generated by Django 4.2.8 on 2025-05-25 08:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_transaction', '0019_remove_gold_transfer_transfer_member_admin_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gold_transfer',
            old_name='transfer_member_amount',
            new_name='transfer_member_amount_received',
        ),
        migrations.AddField(
            model_name='gold_transfer',
            name='transfer_member_admin_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
    ]
