# Generated by Django 4.2.8 on 2025-06-08 07:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_transaction', '0020_rename_transfer_member_amount_gold_transfer_transfer_member_amount_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold_transfer',
            name='transfer_member_admin_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
    ]
