# Generated by Django 4.2.8 on 2025-08-06 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold_transaction', '0023_gold_stock_gold_loan_history_gold_history_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gold_stock',
            old_name='topup_stock',
            new_name='weight',
        ),
    ]
