# Generated by Django 4.2.8 on 2025-08-06 14:55

import core.fields.uuidv7_field
from django.db import migrations
import uuid6


class Migration(migrations.Migration):

    dependencies = [
        ('gold_transaction', '0024_rename_topup_stock_gold_stock_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold_stock',
            name='id',
            field=core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
