# Generated by Django 4.2.8 on 2025-08-14 12:40

import core.fields.uuidv7_field
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gold_transaction', '0025_alter_gold_stock_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='gold_stock_inout',
            fields=[
                ('id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('gold_stock_inout_id', core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, unique=True)),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], max_length=3)),
                ('weight', models.DecimalField(decimal_places=4, max_digits=16)),
                ('stock_before', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('stock_after', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_stock_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gold Stock History',
                'verbose_name_plural': 'Gold Stock Histories',
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
    ]
