# Generated by Django 4.2.8 on 2025-08-14 12:46

import core.fields.uuidv7_field
from django.db import migrations, models
import uuid6


class Migration(migrations.Migration):

    dependencies = [
        ('gold_transaction', '0026_gold_stock_inout'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold_stock',
            name='new_id',
            field=core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='gold_stock',
            name='id',
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
