# Generated by Django 4.2.8 on 2025-08-14 12:48

import core.fields.uuidv7_field
from django.db import migrations
import uuid6


class Migration(migrations.Migration):

    dependencies = [
        ('gold_transaction', '0027_gold_stock_new_id_alter_gold_stock_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gold_stock',
            name='id',
        ),
        migrations.AlterField(
            model_name='gold_stock',
            name='new_id',
            field=core.fields.uuidv7_field.UUIDv7Field(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
